export type ValidSkills =
  | "C#"
  | "ASP.NET WebForms"
  | "ASP.NET Core"
  | "ASP.NET Core API"
  | "Node.js"
  | "Express.js"
  | "React.js"
  | "Next.js"
  | "JavaScript"
  | "TypeScript"
  | "HTML5"
  | "CSS3"
  | "Bootstrap"
  | "Tailwind CSS"
  | "SQL Server"
  | "PostgreSQL"
  | "MySQL"
  | "Firebase"
  | "REST API"
  | "JSON"
  | "Stored Procedures"
  | "Entity Framework"
  | "Git"
  | "GitHub"
  | "Postman"
  | "Visual Studio"
  | "VS Code"
  | "Flutter"
  | "Dart"
  | "Android"
  | "Kotlin"
  | "Modbus TCP"
  | "PLC Integration"
  | "JWT Authentication"
  | "Role Based Access"
  | "Database Design"
  | "OOP"
  | "DBMS"
  | "Data Structures"
  | "Algorithms";

export type ValidCategory =
  | "Full Stack"
  | "Bacnd"
  | "Frontend"
  | "Mobile App"
  | "Database"
  | "API Development"
  | "Industrial Automation"
  | "Enterprise Software";
export type ValidExpType =
  | "Professional"
  | "Personal"
  | "Academic";
export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume"
  | "blogs";
